FROM python:3.11-slim

WORKDIR /app
COPY gen_modbus_tcp.py .
COPY generator_config.yaml .
COPY mait-backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-u", "gen_modbus_tcp.py", "--config", "generator_config.yaml"]
